### ISSUE TITLE
Tessellation - Version 0.1 release

### ISSUE THREAD

**Issue by adachille** [adachille/tessellation#22]
# Tessellation Project - Version 0.1 release

## Description
An MVP version of the project with all the basic foundation built out.

## Criteria
- [x] Basic tessellation generation supported
    - [x] Tessellation generation techniques
        - [x] RNG generator 
        - [x] Genetic Algorithm generator
    - [x] Tessellation types
        - [x] Square translation
- [x] Experiment/example code
    - [x] Examples of different generators
    - [x] Drawing code
- [x] Testing
    - [x] All major code paths are tested
        - [x] Base generation/drawing code - https://github.com/adachille/tessellation/issues/14
        - [x] GA generator - https://github.com/adachille/tessellation/issues/15
    - [x] Add PyLint GitHub action - https://github.com/adachille/tessellation/issues/28
    - [x] Add GitHub workflow for testing + code coverage  - https://github.com/adachille/tessellation/issues/16
